apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.application_name }}
  description: ${{ values.description }}
  annotations:
    vault.io/secrets-path: backstage
    github.com/project-slug: ${{ parameters.orgName }}/${{ values.application_name }}
    argocd/app-name: ${{ values.application_name }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.application_name }}
    backstage.io/kubernetes-label-selector: 'app=${{ values.application_name }}'
  tags:
    - spring-boot
    - java
    - maven
    - kubernetes
    - argocd
    - vault
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - demo-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: The demo API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./swagger/swagger.yaml