apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-argocd-minikube
  title: Spring Boot + ArgoCD + Minikube (Full Flow)
  description: สร้างโปรเจกต์ Spring Boot พร้อมไฟล์ Deployment สำหรับ Minikube/ArgoCD
  tags:
    - spring-boot
    - java
    - maven
    - kubernetes
    - argocd
spec:
  owner: user:guest
  type: microservices

  parameters:
    - title: App Info
      required:
        - application_name
      properties:
        application_name:
          type: string
          default: springboot-argocd-minikube
        description:
          type: string
          default: This is a sample Spring Boot application created by Backstage Software Template
        orgName:
          type: string
          default: ThanutchaiMbix

  steps:
    # 1. create project
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          application_name: ${{ parameters.application_name }}
          image: ghcr.io/${{ parameters.orgName }}/${{ parameters.application_name }}:latest
          description: ${{ parameters.description }}
          orgName: ${{ parameters.orgName }}

    # 2. publish to github
    - id: publish
      name: Publish Repo
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.application_name }}
        defaultBranch: main
        repoVisibility: public

    # 3. register catalog
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    # 4. create argocd app
    - id: argocd
      name: Create ArgoCD App
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/argocd/api/applications
        headers:
          content-type: application/json
        body:
          metadata:
            name: ${{ parameters.application_name }}
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/${{ parameters.orgName }}/${{ parameters.application_name }}.git
              targetRevision: HEAD
              path: k8s
            destination:
              server: https://kubernetes.default.svc
              namespace: demo
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

  output:
    links:
      - title: Repo
        url: ${{ steps.publish.output.remoteUrl }}