apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-app-template
  title: Spring Boot Application with ArgoCD
  description: สร้างโปรเจกต์ Spring Boot พร้อมไฟล์ Deployment สำหรับ Minikube/ArgoCD
  tags:
    - spring-boot
    - java
    - maven
    - kubernetes
    - argocd
spec:
  type: service
  owner: user:guest
  system: microservices

  parameters:
    - title: Provide Application Information
      required:
        - application_name
        - package_name
      properties:
        application_name:
          title: Name
          type: string
          description: ชื่อ App (ควรเป็นภาษาอังกฤษตัวเล็ก เช่น my-app)
        package_name:
          title: Java Package Name
          type: string
          default: com.example.demo
          description: ชื่อ Java package (เช่น com.mbix.service)
        description:
          title: Description
          type: string
        image_name:
          title: Docker Image Name
          type: string
          description: ชื่อ Image ที่จะใช้รัน (เช่น my-registry/my-app:latest)
          default: "nginx:latest"
        orgName:
          title: Organization name
          type: string
          default: ThanutchaiMbix
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./app-template # ชี้ไปที่โฟลเดอร์ skeleton
        values:
          application_name: ${{ parameters.application_name }}
          description: ${{ parameters.description }}
          package_name: ${{ parameters.package_name }}
          image_name: ${{ parameters.image_name }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        # allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.application_name }}
        defaultBranch: ${{ parameters.repoBranchName }}
        repoVisibility: public

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: argocd
      name: Create New Application in Argo CD
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/argocd/api/applications'
        headers:
          content-type: 'application/json'
        body:
          metadata:
            name: ${{ parameters.appName }}
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/${{ parameters.orgName }}/${{ parameters.application_name }}.git
              targetRevision: HEAD
              path: k8s
            destination:
              server: https://kubernetes.default.svc
              namespace: ${{ parameters.namespace }}
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
        
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}