name: Build and Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        # ใช้ shell command โดยตรงเพื่อเลี่ยงปัญหาเรื่อง indentation ของ action
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Image
        run: |
          # ตั้งชื่อ image เป็นตัวพิมพ์เล็ก (Hardcode ชื่อ repo ไปเลยเพื่อความชัวร์)
          IMAGE_ID=ghcr.io/thanutchaimbix/springboot-argocd-minikube
          
          docker build . --file Dockerfile --tag $IMAGE_ID:latest
          docker push $IMAGE_ID:latest