apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.application_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    argocd/app-name: ${{ values.application_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - demo-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: The demo API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./swagger/swagger.yaml