apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.application_name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - pet-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-api
  description: The pet API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./swagger/swagger.yaml